language: ruby
sudo: false
cache: bundler
rvm:
- 2.0.0
- 2.1
- 2.2.0
branches:
  only:
  - master
before_script: bundle exec rake alchemy:spec:prepare
script: bundle exec rspec
env:
- DB=mysql
- DB=postgresql
notifications:
  irc:
    on_success: change
    on_failure: always
    use_notice: true
    channels:
    - irc.freenode.org#alchemy_cms
  slack:
    secure: QzOFw1Ph69pzwWBFgtIVkOnjbcRxB9HPRQ+RYjK+2tg+fsbiTJ+wYgHcZL49tPYcLAls4kymkFWzWBF3PCAXJMfKgUCqXzdQ2FuJC/JoVRTLll4wDnZFPG33jsm5tVznmycZ3ma4+ZWfJQ+C+elEBOba6v1kG9eGIy6sH2cvXfE=
addons:
  code_climate:
    secure: qmOMqc4FUBRP25XqaYIKuxZQ/GrGLKjIc3vUqZa+XfkQKh6xLXvOF7YUM/XJZ5u6D6hk0Ly8UxjctvDY+tQxEAK49lFwK51i7bODfkQjfVBrFzfht7QhxY5HJKx7F0HHmpyNJet4n8mR0gGlhwVyXv+Tz7Rm6O3Hq3+TEbY9+pk=
